server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

features:
  registration: true
  login: true
  search: true   # (Sprint 2)
  review: true   # (Sprint 2)
  updateApp: true # (Sprint 2)

